# Generated by Django 5.0 on 2024-01-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoicedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceDetails',
        ),
    ]
